name: Build documentation and pack
on:
  workflow_dispatch:
  pull_request:
  push:
    branches: [main]
  release:
    types: [published]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  pack:
    name: Generate pack
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Install packages required to generate documentation
        run: |
          sudo apt-get update
          sudo apt-get install --no-install-recommends -y graphviz plantuml

      - name: Fetch tags
        if: github.event_name == 'release'
        run: |
          git fetch --tags --force

      - uses: Open-CMSIS-Pack/gen-pack-action@main
        with:
          doxygen-version: 1.13.2
          packchk-version: 1.4.4
          gen-doc-script: ./DoxyGen/gen_doc.sh
          doc-path: ./Documentation
          gen-pack-script: ./gen_pack.sh --no-preprocess
          gen-pack-output: ./output
          gh-pages-branch: gh-pages
          gh-pages-deploy: gh-pages.yml
